### ISSUE TITLE
'stencil start' unable to consistently read config.json

### ISSUE THREAD

**Issue by digilentSoftware** [bigcommerce/stencil-cli#398]
### Expected behavior
Running 'stencil start' should load the live reload page and refresh as changes are made to config.json

### Actual behavior
Running 'stencil start' loads the live reload page and changes made to config.json cause page to reload but changes are not always reflected in the live page.  Some times the save works with no errors, other times an error message is thrown:

```
Error: C:\Users\digilent\stencil\pw\config.json - Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'
    at Object.parse (C:\Users\digilent\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\lib\json-lint.js:10:19)
    at ThemeConfig.getRawConfig (C:\Users\digilent\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\lib\theme-config.js:379:21)
    at ThemeConfig.getConfig (C:\Users\digilent\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\lib\theme-config.js:57:23)
    at FSWatcher.Bs.watch (C:\Users\digilent\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\bin\stencil-start:193:49)
    at emitThree (events.js:136:13)
    at FSWatcher.emit (events.js:217:7)
    at FSWatcher.<anonymous> (C:\Users\digilent\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\chokidar\index.js:197:38)
    at FSWatcher._emit (C:\Users\digilent\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\chokidar\index.js:238:5)
    at FSWatcher.<anonymous> (C:\Users\digilent\AppData\Roaming\npm\node_modules\@bigcommerce\stencil-cli\node_modules\chokidar\lib\nodefs-handler.js:263:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

### Steps to reproduce behavior
Setup stencil CLI 
Clone cornerstone theme
Run stencil init
Run stencil start
Making changes in config.json and save.  Repeat until failure.

### Additional Notes
We have 3 Windows dev machines setup now with slight variations of the following:
Win 7 / Win 10
Stencil 1.15.1
Node v8.11.0
NPM v5.6.0
Cygwin / Powershell / CMD (with and without admin)

All three systems exhibit this behavior.  One seems to fail less frequently than the others.  
Cornerstone seems to work most often, while other themes like PartsWarehouse fail one almost every save.

I modified the stencil CLI source to print some debug info and it looks like the value being read from config.json is an empty string or only part of the file when the failure occurs.  This causes jsonlint to choke when parsing the file and it seems like a previously cached version is used (hence the changes are not visible in the browser)

I'm happy to collect more info and try any troubleshooting suggestions, just let us know what is helpful.  This is preventing us from moving to our new theme (from blueprint to stencil)

**Comment by digilentSoftware** [comment]
It happens with the default config.json which starts with:

```
{
  "name": "Cornerstone",
  "version": "2.1.0",
  "meta": {
    "price": 0,
...
```

This happens with the released version of the Stencil CLI (installed via NPM), and also with the latest master from Github.  

I added a debug print to **lib/json-lint.js** line 10 and **jsonString** is an empty string when the error occurs.

**Comment by aisflat439** [comment]
What is the name of the project directory in windows? I've found that if the project name is `C:\Users\digilent\Stencil/Client-Project (2)` I get this error.

**Comment by omarolvera** [comment]
I am getting the same error 

Error: C:\Users\digilent\stencil\pw\config.json - Parse error on line 1:

"name": "Cornerstone",
    "version": "2.3.2",

But after get the error I add the command "rs" and apply the changes in the config.json file

**Comment by cypressotter** [comment]
I'm plagued by this error as well. Anyone resolve this?

**Comment by mmooney** [comment]
We're having the same issue.  Most of the time we have to just kill stencil and start it up again

**Comment by junedkazi** [comment]
This issue is fixed in the latest 3.x release. Please give it a try and report if you run into any issues.

**Comment by jjsilas** [comment]
I'm still seeing this issue, with a fresh install of Stencil. In my case, the config.json was not created.

**Comment by timstarkk** [comment]
@jjsilas any solution? I am missing config.json after downloading theme and running stencil init/stencil start
