### ISSUE TITLE
Install fails when using npm@latest (npm 7.23.0 & 7.22.x) on node 12.22.x

### ISSUE THREAD

**Issue by steve-ross** [bigcommerce/stencil-cli#768]
### Expected behavior

`npm i -g @bigcommerce/stencil-cli` succeeds regardless of npm version

### OR

console shows warning that engine declaration does not meet the requirements:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'engine-test@1.0.0',
npm WARN EBADENGINE   required: { node: '>=15.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.15.0', npm: '7.5.3' }
npm WARN EBADENGINE }
```

#### Workaround for NPM 7.x 

```
npm i -g npm@6
npm i -g @bigcommerce/stencil-cli
npm i -g npm@latest
```

### Actual behavior

I receive the following error:
```
npm -v 
# output: 7.23.0

npm i -g @bigcommerce/stencil-cli
...
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/sho-nuff/.nvm/versions/node/v12.22.5/bin/node /Users/sho-nuff/.nvm/versions/node/v12.22.5/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/sho-nuff/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/sho-nuff/.npm/_cacache/tmp/git-cloneiy3mnj
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node scripts/install.js
npm ERR! npm ERR! internal/modules/cjs/loader.js:818
npm ERR! npm ERR!   throw err;
npm ERR! npm ERR!   ^
npm ERR! npm ERR!
npm ERR! npm ERR! Error: Cannot find module 'mkdirp'
npm ERR! npm ERR! Require stack:
npm ERR! npm ERR! - /Users/steveross/.npm/_cacache/tmp/git-cloneiy3mnj/scripts/install.js
npm ERR! npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR! npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
npm ERR! npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR! npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! npm ERR!     at Object.<anonymous> (/Users/sho-nuff/.npm/_cacache/tmp/git-cloneiy3mnj/scripts/install.js:7:13)
npm ERR! npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR! npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR! npm ERR!   requireStack: [
npm ERR! npm ERR!     '/Users/sho-nuff/.npm/_cacache/tmp/git-cloneiy3mnj/scripts/install.js'
npm ERR! npm ERR!   ]
npm ERR! npm ERR! }
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/sho-nuff/.npm/_logs/2021-09-16T17_15_14_315Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sho-nuff/.npm/_logs/2021-09-16T17_15_18_091Z-debug.log
```

### Steps to reproduce behavior

```
npm uninstall -g @bigcommerce/stencil-cli
npm i -g npm@latest
npm i -g @bigcommerce/stencil-cli
```

**Comment by rossyoung5** [comment]
> #### Workaround for NPM 7.x
> ```
> npm i -g npm@6
> npm i -g @bigcommerce/stencil-cli
> npm i -g npm@latest
> ```

The workaround worked for me as well, but yeah it definitely needs to work on latest npm if BC is going to require the update across the board. The changelog makes no mention of stable versions of node or npm needed for this to work:
[https://q8yugwpocmmzdwnkuywv.noticeable.news/publications/required-stencil-cli-version-set-to-3-5-0?header=false&embed=true](https://q8yugwpocmmzdwnkuywv.noticeable.news/publications/required-stencil-cli-version-set-to-3-5-0?header=false&embed=true)

**Comment by steve-ross** [comment]
@rossyoung5 you can try doing a cache clean after you downgrade to npm@6 with `npm cache clean --force`

**Comment by rossyoung5** [comment]
@steve-ross The initial workaround worked fine for me 👍

**Comment by steve-ross** [comment]
@jairo-bc well done! https://github.com/bigcommerce/stencil-cli/commit/5d824094c9a18e23807d432f230b568b918e951a

**Comment by zvuki** [comment]
This is fixed in 3.5.2.

**Comment by steve-ross** [comment]
@zvuki still having an issue installing here the output

```log
~/projects
❯ npm install --cache /tmp/empty-cache -g @bigcommerce/stencil-cli@3.5.2
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated @hapi/vise@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pez@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/nigel@3.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/content@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/file@1.0.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/b64@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/cryptiles@4.2.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/iron@5.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/catbox-memory@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/teamwork@3.3.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/subtext@6.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/somever@2.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/shot@4.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/mimos@4.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/podium@3.4.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/statehood@6.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/heavy@6.2.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/call@5.1.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated @hapi/catbox@10.2.3: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/bounce@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/wreck@15.1.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/ammo@3.1.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/accept@3.2.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@6.2.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated @hapi/boom@8.0.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hapi@18.4.1: This version contains severe security issues and defects and should not be used! Please upgrade to the latest version of @hapi/hapi or consider a commercial license (https://github.com/hapijs/hapi/issues/4114)
npm notice
npm notice New minor version of npm available! 7.23.0 -> 7.24.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.24.0
npm notice Run npm install -g npm@7.24.0 to update!
npm notice
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/booyall/.nvm/versions/node/v12.22.5/bin/node /Users/booyall/.nvm/versions/node/v12.22.5/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/tmp/empty-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node scripts/install.js
npm ERR! npm ERR! internal/modules/cjs/loader.js:818
npm ERR! npm ERR!   throw err;
npm ERR! npm ERR!   ^
npm ERR! npm ERR!
npm ERR! npm ERR! Error: Cannot find module 'mkdirp'
npm ERR! npm ERR! Require stack:
npm ERR! npm ERR! - /private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ/scripts/install.js
npm ERR! npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR! npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
npm ERR! npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR! npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! npm ERR!     at Object.<anonymous> (/private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ/scripts/install.js:7:13)
npm ERR! npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR! npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR! npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR! npm ERR!   requireStack: [
npm ERR! npm ERR!     '/private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ/scripts/install.js'
npm ERR! npm ERR!   ]
npm ERR! npm ERR! }
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /tmp/empty-cache/_logs/2021-09-22T13_51_33_052Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/empty-cache/_logs/2021-09-22T13_51_36_984Z-debug.log

~/projects took 58s
```

### Log File
```log
❯ cat /tmp/empty-cache/_logs/2021-09-22T13_51_33_052Z-debug.log
0 verbose cli [
0 verbose cli   '/Users/booyall/.nvm/versions/node/v12.22.5/bin/node',
0 verbose cli   '/Users/booyall/.nvm/versions/node/v12.22.5/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '--force',
0 verbose cli   '--cache=/tmp/empty-cache',
0 verbose cli   '--prefer-offline=false',
0 verbose cli   '--prefer-online=false',
0 verbose cli   '--offline=false',
0 verbose cli   '--no-progress',
0 verbose cli   '--no-save',
0 verbose cli   '--no-audit',
0 verbose cli   '--include=dev',
0 verbose cli   '--include=peer',
0 verbose cli   '--include=optional',
0 verbose cli   '--no-package-lock-only',
0 verbose cli   '--no-dry-run'
0 verbose cli ]
1 info using npm@7.23.0
2 info using node@v12.22.5
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/Users/booyall/.nvm/versions/node/v12.22.5/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/booyall/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/booyall/.nvm/versions/node/v12.22.5/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 10ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 warn using --force Recommended protections disabled.
27 timing npm:load Completed in 17ms
28 timing arborist:ctor Completed in 1ms
29 timing idealTree:init Completed in 6ms
30 timing idealTree:userRequests Completed in 5ms
31 silly idealTree buildDeps
32 silly placeDep ROOT @bigcommerce/node-sass@3.5.0 OK for:  want: file:../../../../../../../private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ
33 timing idealTree:#root Completed in 7ms
34 timing idealTree:node_modules/@bigcommerce/node-sass Completed in 0ms
35 timing idealTree:buildDeps Completed in 8ms
36 timing idealTree:fixDepFlags Completed in 1ms
37 timing idealTree Completed in 20ms
38 timing reify:loadTrees Completed in 28ms
39 timing reify:diffTrees Completed in 1ms
40 silly reify mark retired [
40 silly reify   '/Users/booyall/.nvm/versions/node/v12.22.5/lib/node_modules/@bigcommerce/node-sass'
40 silly reify ]
41 silly reify moves {
41 silly reify   '/Users/booyall/.nvm/versions/node/v12.22.5/lib/node_modules/@bigcommerce/node-sass': '/Users/booyall/.nvm/versions/node/v12.22.5/lib/node_modules/@bigcommerce/.node-sass-AWDvn7pb'
41 silly reify }
42 timing reify:retireShallow Completed in 3ms
43 timing reify:createSparse Completed in 0ms
44 timing reify:loadBundles Completed in 0ms
45 timing reifyNode:node_modules/@bigcommerce/node-sass Completed in 2ms
46 timing reify:unpack Completed in 2ms
47 timing reify:unretire Completed in 0ms
48 timing build:queue Completed in 0ms
49 timing build:deps Completed in 0ms
50 timing build:queue Completed in 1ms
51 timing build:link:node_modules/@bigcommerce/node-sass Completed in 1ms
52 timing build:link Completed in 1ms
53 info run @bigcommerce/node-sass@3.5.0 install ../../../../../../../private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ node scripts/install.js
54 info run @bigcommerce/node-sass@3.5.0 install { code: 1, signal: null }
55 timing reify:rollback:createSparse Completed in 1ms
56 timing reify:rollback:retireShallow Completed in 1ms
57 timing command:install Completed in 116ms
58 verbose stack Error: command failed
58 verbose stack     at ChildProcess.<anonymous> (/Users/booyall/.nvm/versions/node/v12.22.5/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
58 verbose stack     at ChildProcess.emit (events.js:314:20)
58 verbose stack     at maybeClose (internal/child_process.js:1022:16)
58 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
59 verbose pkgid @bigcommerce/node-sass@3.5.0
60 verbose cwd /private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ
61 verbose Darwin 20.6.0
62 verbose argv "/Users/booyall/.nvm/versions/node/v12.22.5/bin/node" "/Users/booyall/.nvm/versions/node/v12.22.5/lib/node_modules/npm/bin/npm-cli.js" "install" "--force" "--cache=/tmp/empty-cache" "--prefer-offline=false" "--prefer-online=false" "--offline=false" "--no-progress" "--no-save" "--no-audit" "--include=dev" "--include=peer" "--include=optional" "--no-package-lock-only" "--no-dry-run"
63 verbose node v12.22.5
64 verbose npm  v7.23.0
65 error code 1
66 error path /private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ
67 error command failed
68 error command sh -c node scripts/install.js
69 error internal/modules/cjs/loader.js:818
69 error   throw err;
69 error   ^
69 error
69 error Error: Cannot find module 'mkdirp'
69 error Require stack:
69 error - /private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ/scripts/install.js
69 error     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
69 error     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
69 error     at Module.require (internal/modules/cjs/loader.js:887:19)
69 error     at require (internal/modules/cjs/helpers.js:74:18)
69 error     at Object.<anonymous> (/private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ/scripts/install.js:7:13)
69 error     at Module._compile (internal/modules/cjs/loader.js:999:30)
69 error     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
69 error     at Module.load (internal/modules/cjs/loader.js:863:32)
69 error     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
69 error     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
69 error   code: 'MODULE_NOT_FOUND',
69 error   requireStack: [
69 error     '/private/tmp/empty-cache/_cacache/tmp/git-cloneDuO9AJ/scripts/install.js'
69 error   ]
69 error }
70 verbose exit 1

```

**Comment by JDubDev** [comment]
Also still have this issue on a fresh install of Node v12.22.7 & npm v8.1.2 but the rollback to npm v6 still seems to work. Same module error that @steve-ross got above.

**Comment by steve-ross** [comment]
@zvuki still not fixed... duplicated ticket here: #721
